using System.Collections.Generic;
using SchedulingProblem.Model;

namespace SchedulingProblem.Scenarios;

public static class PresentationSchedulingProblem
{
    public static Scenario FMSBasel()
    {
        List<Location> locations = new List<Location>
        {
            new Location(0, "312", new int[]{0}),
            new Location(1, "105", new int[]{0}),
            new Location(2, "106", new int[]{0}),
            new Location(3, "107", new int[]{0}),
            new Location(4, "108", new int[]{0}),
            new Location(5, "109", new int[]{0}),
            new Location(6, "203", new int[]{0}),
            new Location(7, "205", new int[]{0}),
            new Location(8, "206", new int[]{0}),
            new Location(9, "207", new int[]{0}),
            new Location(10, "209", new int[]{0}),
            new Location(11, "210", new int[]{0}),
            new Location(12, "211", new int[]{0}),
            new Location(13, "213", new int[]{0}),
            new Location(14, "217", new int[]{0}),
            new Location(15, "218", new int[]{0}),
            new Location(16, "305", new int[]{0}),
            new Location(17, "306", new int[]{0}),
            new Location(18, "307", new int[]{0}),
            new Location(19, "308", new int[]{0}),
            new Location(20, "310", new int[]{0}),
            new Location(21, "311", new int[]{0}),
            new Location(22, "303", new int[]{1}),
            new Location(23, "320", new int[]{1}),
            new Location(24, "304", new int[]{2}),
            new Location(25, "E11", new int[]{3}),
            new Location(26, "E12", new int[]{3}),
            new Location(27, "U33", new int[]{0}),
            new Location(28, "E05", new int[]{0}),
            new Location(29, "E06", new int[]{0}),
            new Location(30, "E09", new int[]{0}),
            new Location(31, "E14", new int[]{0}),
            new Location(32, "E17", new int[]{0}),
        };

        List<Person> teachers = new List<Person>
        {
            new Person(0, "abu", 100, new int[] { }, new int[] { }, 1,1),
            new Person(1, "baa", 100, new int[] { }, new int[] { }, 1,1),
            new Person(2, "bae", 100, new int[] { }, new int[] { }, 1,1),
            new Person(3, "bak", 100, new int[] { }, new int[] { }, 1,1),
            new Person(4, "ben", 100, new int[] {0,1,13,14,15,16,17}, new int[] { }, 1,1),
            new Person(6, "bim", 100, new int[] { }, new int[] { }, 1,1),
            new Person(7, "bov", 100, new int[] { }, new int[] { }, 1,1),
            new Person(8, "bra", 100, new int[] { }, new int[] { }, 1,1),
            new Person(9, "brr", 100, new int[] { }, new int[] { }, 1,1),
            new Person(10, "brm", 100, new int[] { }, new int[] { }, 1,1),
            new Person(11, "bus", 100, new int[] { }, new int[] { }, 1,1),
            new Person(12, "cad", 100, new int[] { }, new int[] { }, 1,1),
            new Person(13, "chp", 100, new int[] { }, new int[] { }, 1,1),
            new Person(14, "dcv", 100, new int[] { }, new int[] { }, 1,1),
            new Person(15, "det", 100, new int[] { }, new int[] { }, 1,1),
            new Person(16, "dil", 100, new int[] { }, new int[] { }, 1,1),
            new Person(17, "dua", 100, new int[] { }, new int[] { }, 1,1),
            new Person(18, "ehv", 100, new int[] { }, new int[] { }, 1,1),
            new Person(19, "eqn", 100, new int[] { }, new int[] { }, 1,1),
            new Person(20, "ert", 100, new int[] { }, new int[] { }, 1,1),
            new Person(21, "feb", 100, new int[] { }, new int[] { }, 1,1),
            new Person(22, "fre", 100, new int[] { }, new int[] { }, 1,1),
            new Person(23, "fus", 100, new int[] { }, new int[] { }, 1,1),
            new Person(24, "gad", 100, new int[] { }, new int[] { }, 1,1),
            new Person(25, "gaf", 100, new int[] { }, new int[] { }, 1,1),
            new Person(26, "gai", 100, new int[] {13,14,15,16,17}, new int[] { }, 1,1),
            new Person(27, "grp", 100, new int[] { }, new int[] { }, 1,1),
            new Person(28, "gra", 100, new int[] { }, new int[] { }, 1,1),
            new Person(29, "grn", 100, new int[] { }, new int[] { }, 1,1),
            new Person(30, "gta", 100, new int[] { }, new int[] { }, 1,1),
            new Person(31, "gua", 100, new int[] { }, new int[] { }, 1,1),
            new Person(32, "gut", 100, new int[] { }, new int[] { }, 1,1),
            new Person(33, "gyt", 100, new int[] { }, new int[] { }, 1,1),
            new Person(34, "heb", 100, new int[] { }, new int[] { }, 1,1),
            new Person(35, "hem", 100, new int[] { }, new int[] { }, 1,1),
            new Person(36, "her", 100, new int[] { }, new int[] { }, 1,1),
            new Person(37, "hey", 100, new int[] { }, new int[] { }, 1,1),
            new Person(38, "his", 100, new int[] {0,1,2,3,4,12,13,14,15,16,17}, new int[] { }, 1,1),
            new Person(39, "Hey", 100, new int[] { }, new int[] { }, 1,1),
            new Person(40, "hom", 100, new int[] { }, new int[] { }, 1,1),
            new Person(41, "hus", 100, new int[] { }, new int[] { }, 1,1),
            new Person(42, "jep", 100, new int[] { }, new int[] { }, 1,1),
            new Person(43, "jer", 100, new int[] { }, new int[] { }, 1,1),
            new Person(44, "jew", 100, new int[] { }, new int[] { }, 1,1),
            new Person(45, "joa", 100, new int[] { }, new int[] { }, 1,1),
            new Person(46, "kib", 100, new int[] { }, new int[] { }, 1,1),
            new Person(47, "kln", 100, new int[] { }, new int[] { }, 1,1),
            new Person(48, "kng", 100, new int[] { }, new int[] { }, 1,1),
            new Person(49, "kuo", 100, new int[] { }, new int[] { }, 1,1),
            new Person(50, "kür", 100, new int[] { }, new int[] { }, 1,1),
            new Person(51, "lej", 100, new int[] { }, new int[] { }, 1,1),
            new Person(52, "lee", 100, new int[] { }, new int[] { }, 1,1),
            new Person(53, "lem", 100, new int[] { }, new int[] { }, 1,1),
            new Person(54, "ler", 100, new int[] { }, new int[] { }, 1,1),
            new Person(55, "löf", 100, new int[] { }, new int[] { }, 1,1),
            new Person(56, "lum", 100, new int[] { }, new int[] { }, 1,1),
            new Person(57, "mar", 100, new int[] { }, new int[] { }, 1,1),
            new Person(58, "med", 100, new int[] { }, new int[] { }, 1,1),
            new Person(59, "mey", 100, new int[] { }, new int[] { }, 1,1),
            new Person(60, "mid", 100, new int[] { }, new int[] { }, 1,1),
            new Person(61, "mef", 100, new int[] { }, new int[] { }, 1,1),
            new Person(62, "moa", 100, new int[] { }, new int[] { }, 1,1),
            new Person(63, "mus", 100, new int[] { }, new int[] { }, 1,1),
            new Person(64, "nin", 100, new int[] { }, new int[] { }, 1,1),
            new Person(65, "oem", 100, new int[] { }, new int[] { }, 1,1),
            new Person(66, "orm", 100, new int[] { }, new int[] { }, 1,1),
            new Person(67, "pes", 100, new int[] {0,1,2,3,4,5,6,7,11,12,16,17}, new int[] { }, 1,1),
            new Person(68, "pfl", 100, new int[] { }, new int[] { }, 1,1),
            new Person(69, "pib", 100, new int[] { }, new int[] { }, 1,1),
            new Person(70, "piv", 100, new int[] {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17}, new int[] { }, 1,1),
            new Person(71, "ple", 100, new int[] { }, new int[] { }, 1,1),
            new Person(72, "pli", 100, new int[] { }, new int[] { }, 1,1),
            new Person(73, "pum", 100, new int[] { }, new int[] { }, 1,1),
            new Person(74, "rec", 100, new int[] { }, new int[] { }, 1,1),
            new Person(75, "ref", 100, new int[] { }, new int[] { }, 1,1),
            new Person(76, "ren", 100, new int[] { }, new int[] { }, 1,1),
            new Person(77, "rod", 100, new int[] {0,1,2,3}, new int[] { }, 1,1),
            new Person(78, "rok", 100, new int[] { }, new int[] { }, 1,1),
            new Person(79, "ros", 100, new int[] { }, new int[] { }, 1,1),
            new Person(80, "rus", 100, new int[] { }, new int[] { }, 1,1),
            new Person(81, "rut", 100, new int[] { }, new int[] { }, 1,1),
            new Person(82, "Ruf", 100, new int[] { }, new int[] { }, 1,1),
            new Person(83, "sca", 100, new int[] { }, new int[] { }, 1,1),
            new Person(84, "scd", 100, new int[] { }, new int[] { }, 1,1),
            new Person(85, "scf", 100, new int[] {4,5,6,7,8,9,10,11}, new int[] { }, 1,1),
            new Person(86, "scj", 100, new int[] { }, new int[] { }, 1,1),
            new Person(87, "scm", 100, new int[] { }, new int[] { }, 1,1),
            new Person(88, "scp", 100, new int[] { }, new int[] { }, 1,1),
            new Person(89, "srm", 100, new int[] { }, new int[] { }, 1,1),
            new Person(90, "scs", 100, new int[] { }, new int[] { }, 1,1),
            new Person(91, "sct", 100, new int[] {13,14,15,16,17}, new int[] { }, 1,1),
            new Person(92, "str", 100, new int[] { }, new int[] { }, 1,1),
            new Person(93, "stt", 100, new int[] { }, new int[] { }, 1,1),
            new Person(94, "stm", 100, new int[] { }, new int[] { }, 1,1),
            new Person(95, "tem", 100, new int[] { }, new int[] { }, 1,1),
            new Person(96, "thb", 100, new int[] { }, new int[] { }, 1,1),
            new Person(97, "thc", 100, new int[] { }, new int[] { }, 1,1),
            new Person(98, "trd", 100, new int[] { }, new int[] { }, 1,1),
            new Person(99, "urk", 100, new int[] { }, new int[] { }, 1,1),
            new Person(100, "vau", 100, new int[] {0,1,2,3}, new int[] { },1, 1),
            new Person(101, "was", 100, new int[] { }, new int[] { },1, 1),
            new Person(102, "wea", 100, new int[] { }, new int[] { },1, 1),
            new Person(103, "wei", 100, new int[] { }, new int[] { },1, 1),
            new Person(104, "wem", 100, new int[] { }, new int[] { },1, 1),
            new Person(105, "wam", 100, new int[] { }, new int[] { },1, 1),
            new Person(106, "wic", 100, new int[] { }, new int[] { },1, 1),
            new Person(107, "wij", 100, new int[] { }, new int[] { },1, 1),
            new Person(108, "wis", 100, new int[] {13,14,15,16,17}, new int[] { },1, 1),
            new Person(109, "wys", 100, new int[] {8,9}, new int[] { },1, 1),
            new Person(110, "zad", 100, new int[] {5,6,7,8,9,10,11,12}, new int[] { },1, 1),
            new Person(111, "zum", 100, new int[] { }, new int[] { },1, 1),
            new Person(112, "zwm", 100, new int[] { }, new int[] { },1, 1),
        };

        List<TimeSlot> ts = new List<TimeSlot>
        {
            new TimeSlot(0, "Fr 08:00"),
            new TimeSlot(1, "Fr 08:45"),
            new TimeSlot(2, "Fr 09:30"),
            new TimeSlot(3, "Fr 10:15"),
            new TimeSlot(4, "Fr 11:00"),
            new TimeSlot(5, "Fr 11:45"),
            new TimeSlot(6, "Fr 12:30"),
            new TimeSlot(7, "Fr 13:30"),
            new TimeSlot(8, "Fr 14:15"),
            new TimeSlot(9, "Fr 15:00"),
            new TimeSlot(10, "Fr 15:45"),
            new TimeSlot(11, "Fr 16:30"),
            new TimeSlot(12, "Fr 17:15"),
            new TimeSlot(13, "Sa 08:00"),
            new TimeSlot(14, "Sa 08:45"),
            new TimeSlot(15, "Sa 09:30"),
            new TimeSlot(16, "Sa 10:15"),
            new TimeSlot(17, "Sa 11:00"),
        };

        var tasks = new List<SchedulingTask>
        {
            new SchedulingTask(0  ,"Third Culture Kids: Aufwachsen in mehreren Kulturen ",1,2,new int[]{79,3},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(1  ,"Wie stehen die Schweiz und die Türkei zueinander",1,2,new int[]{15,73},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(2  ,"Die weltweite Kinderarbeit was steckt wirklich dahinter?",1,2,new int[]{6,78},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(3  ,"Akzeptanz des Schwimmsports in der Gesellschaft",1,2,new int[]{110,78},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(4  ,"Wie mache ich neue Muskeln?",1,2,new int[]{110,78},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(5  ,"Spanische Grippe und die parallelen zum Corona Virus",1,2,new int[]{6,21},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(6  ,"Was steckt hinter dem Phänomen K-Pop?",1,2,new int[]{68,83},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(7  ,"Leonhard Euler",1,2,new int[]{110,50},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(8  ,"Supplements",1,2,new int[]{63,85},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(9  ,"Der biologische Zyklus der Menstruation",1,2,new int[]{29,108},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(10 ,"Das Coronavirus und seine Folgen: Das psychologische Verhalten der Menschen wärend der Coronakrise",1,2,new int[]{23,3},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(11 ,"Im Visier des 2. Weltkriegs",1,2,new int[]{6,110},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(12 ,"Zwangsheirat im Vergleich zu früher und heute",1,2,new int[]{79,23},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(13 ,"Wie hat sich Stress im Jugendalter in den letzten 30 Jahren verändert",1,2,new int[]{79,23},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(14 ,"Sollte in den Schulen mehr Wert auf politische Bildung gelegt werden?",1,2,new int[]{79,95},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(15 ,"Vertiefung in die VFX-Welt",1,2,new int[]{58,7},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(16 ,"Essstörungen bei Jugendlichen",1,2,new int[]{30,88},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(17 ,"Heilmittel aus dem Garten",1,2,new int[]{29,41},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(18 ,"Ein Blick durch die Türkei",1,2,new int[]{15,73},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(19 ,"Wie reagiert mein Körper, wenn ich Vegetarierin werde?",1,2,new int[]{29,64},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(20 ,"Wie hat sich die Fussballwelt vor 40 Jahren zu heute verändert?",1,2,new int[]{9,45},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(21 ,"Bestrahlungsmethoden und den Vergleich zu Greys Anatomy",1,2,new int[]{80,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(22 ,"Canabis als Medizin: Teufelskraut oder Wunderblüte?",1,2,new int[]{91,21},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(23 ,"Drei Wochen ohne Fertigprodukte",1,2,new int[]{64,106},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(24 ,"Die Behandlungsmethoden bei Akne",1,2,new int[]{80,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(25 ,"Tattoos: Welche Auswirkungen bringen Tattoos am Körper?",1,2,new int[]{85,107},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(26 ,"Gesunde Ernährung im Alter",1,2,new int[]{106,9},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(27 ,"Power bar",1,2,new int[]{80,35},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(28 ,"Methoden zur Rauchentwöhnung",1,2,new int[]{80,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(29 ,"Modellbau Landschaft und erneuerbare Energie",1,2,new int[]{96,101},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(30 ,"\"Das Leben mit Alzheimer\"",1,2,new int[]{63,107},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(31 ,"Rehabilitation im Leistungssport",1,2,new int[]{33,106},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(32 ,"Das Phänomen der Synästhesie",1,2,new int[]{46,9},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(33 ,"Methoden um schneller einzuschlafen",1,2,new int[]{63,91},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(34 ,"Bier selbstgebraut",1,2,new int[]{80,91},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(35 ,"Heilmittel aus Kräutern herstellen: Kräuterprodukte zur Haarpflege ",1,2,new int[]{91,24},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(36 ,"Ist es wahrscheinlich?",1,2,new int[]{107,50},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(37 ,"Wie wichtig ist Ernährung im Kraftsport",1,2,new int[]{80,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(38 ,"Mysterien des Universums",1,2,new int[]{107,63},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(39 ,"Welche Auswirkungen hat Pilates auf Körper und Geist?",1,2,new int[]{104,12},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(40 ,"Dunking my Vision - Sprungkrafttraining",1,2,new int[]{106,33},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(41 ,"Junge Mütter - Wie verändert sich das Leben?",1,2,new int[]{65,74},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(42 ,"Inwiefern kann Sport bei Verhaltensstörungen als Selbsthilfe dienen?",1,2,new int[]{15,14},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(43 ,"Die Sprachentwicklung bei Kindern - Wenn aus Sätzen Laute werden.",1,2,new int[]{65,72},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(44 ,"Neues FMS-Kompakt",1,2,new int[]{20,96},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(45 ,"Freestyletrampolin für Anfänger",1,2,new int[]{93,106},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(46 ,"Make-up your Look: Kreative und preisgünstige Make-up Looks zum Nachschminken",1,2,new int[]{87,93},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(47 ,"The Scottish Clans",1,2,new int[]{87,58},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(48 ,"Judobuch für Anfänger",1,2,new int[]{93,58},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(49 ,"Entwicklung der Jugendlichen in Ein-Eltern-Familien",1,2,new int[]{83,66},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(50 ,"Fatih Sultan Mehmet und die Eroberung von Konstantinopel ",1,2,new int[]{15,14},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(51 ,"Musikstücke zu Emotionen komponieren",1,2,new int[]{69,111},new int[] {},new int[] {},new int[]{1}),
            new SchedulingTask(52 ,"Erhöht Sport die Denkfähigkeit?",1,2,new int[]{26,41},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(53 ,"Der grösste Chemieunfall Basels",1,2,new int[]{6,110},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(54 ,"Das kreative Lernen der Buchstaben. Die farbenfrohen Buchstaben, die dein Wissen verändern.",1,2,new int[]{56,96},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(55 ,"Das Kistenbuch für den Tag. Lernhilfen für Kinder zwischen 3 - 5 Jahren",1,2,new int[]{56,96},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(56 ,"Herstellung eines eigenen Boards",1,2,new int[]{58,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(57 ,"Modellbau Landschaft und erneuerbare Energie",1,2,new int[]{96,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(58 ,"Non-verbale Kommunikation und Emotionen",1,2,new int[]{65,74},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(59 ,"Was ist effizienter? Spielen oder Korbtraining",1,2,new int[]{33,64},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(60 ,"Komposition",1,2,new int[]{38,67},new int[] {},new int[] {},new int[]{1}),
            new SchedulingTask(61 ,"Angst in die Schule zu gehen?",1,2,new int[]{65,106},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(62 ,"Trag mich neu!",1,2,new int[]{103,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(63 ,"Gibt es sowas wie eine Zwillinsbindung? und wie wirkt sie sich auf die Identitätsentwicklung aus?",1,2,new int[]{65,72},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(64 ,"Ein Bild zeigt mehr als tausend Worte",1,2,new int[]{87,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(65 ,"Zwischen zwei Welten - Das Leben mit mehreren Kulturen",1,2,new int[]{66,65},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(66 ,"Wie gehen Filme mit wahren Ereignissen um?",1,2,new int[]{20,103},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(67 ,"Ein Solotanz über häusliche Gewalt",1,2,new int[]{12,104},new int[] {},new int[] {},new int[]{2}),
            new SchedulingTask(68 ,"Lernhilfe zur Staatskunde",1,2,new int[]{28,14},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(69 ,"Re-Cycling",1,2,new int[]{56,93},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(70 ,"Kinderbuch",1,2,new int[]{65,97},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(71 ,"Das Leben im Heim",1,2,new int[]{25,87},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(72 ,"Speed Reading ",1,2,new int[]{87,55},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(73 ,"Glücksgefühl im Sport - Sportsucht",1,2,new int[]{25,104},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(74 ,"Integration von Lernschwächen SuS in den baselstädtischen Regelklassen",1,2,new int[]{25,79},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(75 ,"Mobbing auf der Primarstufe",1,2,new int[]{72,65},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(76 ,"Die Kraft aus dem Korn",1,2,new int[]{64,29},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(77 ,"Die steinerne Schatzsuche",1,2,new int[]{97,93},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(78 ,"Fehlernährung",1,2,new int[]{24,91},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(79 ,"Mein eigener Song in Begleitung von einem neu erlernten Instrument",1,2,new int[]{69,38},new int[] {},new int[] {},new int[]{1}),
            new SchedulingTask(80 ,"Kinderbuch verbunden mit Kinderschwimmen: Willi geht schwimmen",1,2,new int[]{16,97},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(81 ,"Wie kann Betroffenen mit Alopecia Areata geholfen werden?",1,2,new int[]{4,103},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(82 ,"Marokkanisches Geschirrset aus Porzellan",1,2,new int[]{56,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(83 ,"Fotografie",1,2,new int[]{96,20},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(84 ,"Do young girls need representation in their toys?",1,2,new int[]{68,45},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(85 ,"Zerbrochene Schönheit (Kleopatra als Glasbüste)",1,2,new int[]{56,93},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(86 ,"Architektur Basel",1,2,new int[]{96,97},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(87 ,"Reportage",1,2,new int[]{3,102},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(88 ,"Träume zeichnen ",1,2,new int[]{100,8},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(89 ,"Die Welt der griechischen Mythen darstellen",1,2,new int[]{96,16},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(90 ,"Design und Bau einer Lagerküche",1,2,new int[]{101,97},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(91 ,"Das perfekte Strategiespiel",1,2,new int[]{58,88},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(92 ,"Reau Erno (Egal wie unterschiedlich wir sind, Emotionen tragen wir alle",1,2,new int[]{20,106},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(93 ,"Tonplastik einer starken Frau",1,2,new int[]{56,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(94 ,"Detail in Miniaturenmalerei",1,2,new int[]{58,100},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(95 ,"Grüne Oliven",1,2,new int[]{20,16},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(96 ,"seven deadly sins",1,2,new int[]{20,93},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(97 ,"Gesellschaftskritischer Dialog filmisch festgehalten",1,2,new int[]{7,20},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(98 ,"Rework fashion / aus alt wird neu",1,2,new int[]{103,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(99 ,"\"Social Media\" versus \"Social life\"",1,2,new int[]{100,7},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(100,"Eine Konstruktion für ein Wildbienenhaus für die FMS",1,2,new int[]{101,58},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(101,"Wie viel Materielles brauchen wir um erfüllt zu sein?",1,2,new int[]{88,49},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(102,"Gibt es Unterschiede in der non-verbaren kommunikation zwischen Mann und Frau",1,2,new int[]{3,102},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(103,"Kondition mit verschiedenen Techniken aufbauen",1,2,new int[]{66,41},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(104,"Was macht einen Menschen einflussreich?",1,2,new int[]{14,23},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(105,"Die Selbst- und Fremdwahrnehmung",1,2,new int[]{77,41},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(106,"Einfluss von Geschwistern auf soziales Verhalten",1,2,new int[]{46,49},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(107,"Die Wirkung von Schulstress auf die Psyche",1,2,new int[]{46,49},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(108,"Die Entwicklung von Zeichnungen",1,2,new int[]{46,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(109,"Kinderbuch über unser Sonnensystem",1,2,new int[]{49,100},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(110,"Aus Brüdern wurden Feinde",1,2,new int[]{28,0},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(111,"Wie wirken sich Drogen auf die Psyche aus",1,2,new int[]{46,15},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(112,"Geschichte Finnlands: Die Entstehung des Finnischen Staates",1,2,new int[]{0,102},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(113,"Probleme der modernen Gesellschaft",1,2,new int[]{49,95},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(114,"Kunsttherapeutische Massnahmen in der Sozialen Arbeit",1,2,new int[]{16,93},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(115,"Ist das Voraussagen eines Fussballspiels möglich oder Glück?",1,2,new int[]{33,110},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(116,"Herbizide in Lebensmitteln",1,2,new int[]{85,63},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(117,"Das ABC der Kinder",1,2,new int[]{16,7},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(118,"Gefahren im Universum",1,2,new int[]{53,41},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(119,"Die fünf Weltreligionen im Vergleich",1,2,new int[]{0,88},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(120,"Can I express my feelings through art?",1,2,new int[]{7,16},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(121,"Portrais mit verschiedenen Maltechniken",1,2,new int[]{7,16},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(122,"Das Internet als Goldgrube",1,2,new int[]{83,33},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(123,"Glasknochenkrankheit - wie schwer ist der Alltag?",1,2,new int[]{4,24},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(124,"Ein Malbuch mit Kindergeschichten zwischen 8-9 Jahre",1,2,new int[]{15,97},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(125,"Erleichtert das Bullet Journaling unser Leben?",1,2,new int[]{77,55},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(126,"Untersuchungen und Erkenntnisse des Strafvollzugs in Basel",1,2,new int[]{66,98},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(127,"Unterschied zwischen Frauenfussball und Männerfussball",1,2,new int[]{63,85},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(128,"Evolution des Internets - Internetgenerationen",1,2,new int[]{107,63},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(129,"Würfelpowerball zum Aufwärmen der Muskeln",1,2,new int[]{33,25},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(130,"Meinung des Mittleren Ostens über die Schweiz/arabaische Integration in der Schweiz",1,2,new int[]{81,18},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(131,"Das Leben mit Borderline",1,2,new int[]{77,93},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(132,"Eine Wanderung führt zu einer Trilogie",1,2,new int[]{97,93},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(133,"Der richtige Weg",1,2,new int[]{81,12},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(134,"Hygiene",1,2,new int[]{63,85},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(135,"Kopfbedeckung in verschiedenen Kulturen",1,2,new int[]{101,16},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(136,"Warum besitzen 35 Millionen Menschen kein Land?",1,2,new int[]{81,91},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(137,"Diagnose Gehirntumor: Fokus auch auf den Prozess (Untersuchung) ",1,2,new int[]{63,107},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(138,"Armut in Sri Lanka nach dem Bürgerkrieg und dem Tsunami",1,2,new int[]{18,81},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(139,"Was genau ist Multiple Sklerose oder auch MS genannt?",1,2,new int[]{63,107},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(140,"Einfluss der Ernährung auf den Muskelaufbau",1,2,new int[]{85,63},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(141,"Das Leben als Veganer",1,2,new int[]{107,85},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(142,"Auswirkung von Krebsdiagnose auf das soziale Umfeld",1,2,new int[]{64,104},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(143,"Wirkungsweise der Blutegeltherapie bei Schmerzpatienten",1,2,new int[]{53,21},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(144,"Postmoderne - Punk",1,2,new int[]{103,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(145,"Musik komponieren",1,2,new int[]{69,67},new int[] {},new int[] {},new int[]{1}),
            new SchedulingTask(146,"Wie beeinflusst ein Trauma die Entwicklung eines Kindes?",1,2,new int[]{65,74},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(147,"Die Emotionen beim Lesen",1,2,new int[]{3,52},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(148,"Selbst erfundene Dessertrezepte mit Beeren",1,2,new int[]{24,87},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(149,"Geschlechterspezifische Verhaltensweisen im öffentlichen Raum",1,2,new int[]{8,95},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(150,"Was wäre wenn?",1,2,new int[]{83,68},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(151,"Mein daHEIM",1,2,new int[]{93,77},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(152,"Stress",1,2,new int[]{77,95},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(153,"Selbstgenähter Lehenga",1,2,new int[]{93,101},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(154,"Fitness und Psychologie",1,2,new int[]{93,77},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(155,"Beste Freunde und Peers im Jugendalter",1,2,new int[]{65,8},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(156,"Surreal, real, traumhaft schön?",1,2,new int[]{93,97},new int[] {},new int[] {},new int[]{3}),
            new SchedulingTask(157,"Inwiefern ist die Idee von Neve Shalom geeignet um den Nahost Konflikt zu lösen",1,2,new int[]{83,45},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(158,"Hypnose - Das Unterbewusstsein als Ressurce",1,2,new int[]{30,3},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(159,"Wie Geschlechtsrollen unsere Art zu lieben beeinflussen",1,2,new int[]{65,74},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(160,"Meine Grenze und die der Anderen",1,2,new int[]{83,9},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(161,"Was macht einen Krimi aus und wie schreibt man selber einen",1,2,new int[]{3,52},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(162,"Was ist die Realität der Frauen die in Mexiko leben?",1,2,new int[]{8,79},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(163,"Das Leben als Zwilling - Fluch oder Segen?",1,2,new int[]{3,30},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(164,"Unterschied zwischen dem Frauen- und Männerfussball: Unterschiede in der Psychologie und Physio",1,2,new int[]{30,49},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(165,"Geschichte und Menschlichkeit (hat noch keinen Titel)",1,2,new int[]{83,68},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(166,"Selbst erfundene Dessertrezepte mit Schokolade",1,2,new int[]{24,87},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(167,"Das Essen am Schwarzen Meer",1,2,new int[]{15,59},new int[] {},new int[] {},new int[]{0}),
            new SchedulingTask(168,"Ein Vergleich von konventionellen Kleidertextilien aus Baumwolle und Alternativen wie Bambus auf ihre Nachhaltigkeit",1,2,new int[]{34,41},new int[] {},new int[] {},new int[]{0}),
        };

        var skills = new List<Skill> { new(0, "normal"), new(1, "music"), new(2, "dance"), new(3, "art") };

        var scenario = new Scenario(teachers, ts, tasks, locations, skills);
        return scenario;
    }
}